[package]
name = "http-request"
version = "2.0.0"
edition = "2021"
authors = ["ltpp-universe <root@ltpp.vip>"] 
license = "MIT"
description = "Http request is a lightweight, efficient library for building, sending, and handling HTTP requests in Rust applications."
keywords = ["http", "request", "response", "tcp", "send"]
repository = "https://github.com/ltpp-universe/http-request.git"

[dependencies]
hex = "0.4.3"
native-tls = "0.2.12"
serde = "1.0.215"
serde-xml-rs = "0.6.0"
serde_json = "1.0.133"
serde_urlencoded = "0.7.1"
url = "2.5.4"
urlencoding = "2.1.3"

[dev-dependencies]
color-output = "4.0.0"
std-macro-extensions = "0.16.0"
