[package]
name = "http-request"
version = "1.0.1"
edition = "2021"
authors = ["ltpp-universe <root@ltpp.vip>"] 
license = "MIT"
description = "Http request is a lightweight, efficient library for building, sending, and handling HTTP requests in Rust applications."
keywords = ["http", "request", "response", "tcp", "send"]
repository = "https://github.com/ltpp-universe/http-request.git"

[dependencies]
url = "2.5.4"

[dev-dependencies]
color-output = "3.0.1"
std-macro-extensions = "0.16.0"
